name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My Email is 22f2000813@ds.study.iitm.ac.in  # Email in the name
        run: echo "Hello, world!"
